<?php
namespace App\Constants;
class Constants
{
    const SESSION_KEY_AUCTIONEER = 'session_key_auctioneer';
    const SESSION_KEY_USER = 'session_key_user';
    const SESSION_KEY_ADMIN = 'SESSION_KEY_ADMIN';
    const RESPONSE_STATUS_SUCCESS = 'success';
    const RESPONSE_STATUS_ERROR = 'error';
    const RESPONSE_STATUS_ACCESS_IS_DENIED = 'access is denied';
    const RESPONSE_MESSAGE_INVALID_INPUT = 'Invalid input';
    const RESPONSE_MESSAGE_INVALID_USER = 'Invalid email or password';
    const RESPONSE_MESSAGE_AUCTIONEER_NOT_FOUND = 'Auctioneer not exist';
    const RESPONSE_MESSAGE_AUCTION_NOT_FOUND = 'Auction not exist';
    const RESPONSE_MESSAGE_LOT_NOT_FOUND = 'Lot not exist';
    const RESPONSE_MESSAGE_DELETE_FAILED = 'deleting failed';
    const RESPONSE_MESSAGE_DELETE_OK = 'delete successful';
    const RESPONSE_MESSAGE_PHONE_NUMBER_EXISTED = 'Phone number existed';
    const RESPONSE_MESSAGE_FAX_NUMBER_EXISTED = 'Fax number existed';
    const RESPONSE_MESSAGE_CARD_NUMBER_EXISTED = 'Card number existed';
    const RESPONSE_MESSAGE_CANT_UPLOAD_IMAGE = 'Can not upload image';
    const RESPONSE_MESSAGE_INFO_NOT_FOUND = 'No infomation available';
    const RESPONSE_MESSAGE_OUT_OF_CONSIGNMENT_CLOSES = 'Out of consignment close date';
    const RESPONSE_MESSAGE_USER_PAYMENT_NOT_FOUND = "User's payment is not exist";
    const RESPONSE_MESSAGE_EMAIL_EXISTED = 'Email existed';
    const RESPONSE_MESSAGE_USER_NOT_FOUND = 'User not exist';
    const RESPONSE_MESSAGE_COUPON_EXISTED = 'Coupon code existed';
    const RESPONSE_MESSAGE_COUPON_NOT_FOUND = 'Coupon code does not exist';
    const RESPONSE_MESSAGE_PACKAGE_NOT_FOUND = 'Package not exist';
    const RESPONSE_MESSAGE_SUBCATEGORY_NOT_FOUND = 'Subcategory not exist';
    const RESPONSE_MESSAGE_INVALID_FILE_TYPE = 'Invalid file type';
    const RESPONSE_MESSAGE_INVALID_CSV_FILE_NAME = 'Invalid csv file name';
    const RESPONSE_MESSAGE_INVALID_ZIP_FILE_NAME = 'Invalid zip file name';
    const CSV_FILE_URL = 'excel/';
    const ZIP_FILE_URL = 'zip_file/';
    const LOT_UPLOAD_FILE_URL = 'lot_upload_file/';
    const API_URL = 'http://tractorzoom.dev/';
    //const API_URL = 'http://api.tractorzoom.qa.pgtest.co:2016/';
    const WEB_URL = 'http://tractorzoom.qa.pgtest.co:2016/';
    const MOBILE_DETECT_LINK = Constants::API_URL.'mobiledetect?token=';
    const DESTINATION_LINK = 'http://tractorzoom.qa.pgtest.co:2016/#/core/resetPassword?token=';
    const APP_WEB_DESTINATION_LINK = 'http://tractorzoom.uat.pgtest.co/#/core/resetPasswordMobile?token=';
    const APP_DESTINATION_LINK = 'tractorzoom://?token=';
    const LOT_IMAGE_URL = 'images/lots/';
    const AUCTIONEER_LOGO_URL = 'images/auctioneerlogo/';
    const TRACTOR_ZOOM_LOGO = 'images/tractorzoom/';
    const FROM_EMAIL = 'vietdv9356@gmail.com';
    const AUCTION_STATUS_PUBLISHED = 1;
    const AUCTION_STATUS_UNPUBLISHED = 2;
    const AUCTION_STATUS_AWATING_RESULT = 3;
    const AUCTION_STATUS_COMPLETED = 4;
    const LOT_TYPE_BASIC = 1;
    const LOT_TYPE_FEATURE = 2;
    const SOLD = 1;
    const NO_SALE = 0;
    const CONSIGNMENT = 2;
    const LIMIT_VALUE = 4;
    const LIMIT_LOT = 10;
    const AUCTIONEER = 1;
    const USER = 2;
    const ADMIN = 3;
    const SUPER_ADMIN = 4;
    const UNCLAIM_MONEY = 25;
    const CONCIERGE_MONEY = 40;
    const RUN_TIME = 15;
    const PAYMENT_SECRET_KEY = 'sk_test_rVpNzJowgFakoFWVz1pYq00P';
    const SUPPORT_EMAIL = 'support@tractorzoom.com';
    const RECIEVE_EMAIL = 'viet.dovan@powergatesoftware.com';
}
?>